[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "python -m streamlit run streamlit_app.py --server.address 0.0.0.0 --server.port $PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
